name: Lint

on: [push]

jobs:
  xml-linters:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Lint MAE
      uses: ChristophWurst/xmllint-action@v1
      with:
        xml-file: ./tei/image-four-living-creatures.xml
        xml-schema-file: ./tei_all.rng
