name: Lint

on: [push]

jobs:
  xml-linters:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Download schema file 1
      run: wget https://tei-c.org/release/xml/tei/custom/schema/xsd/tei_all.xsd
    - name: Download schema file 2
      run: wget https://tei-c.org/release/xml/tei/custom/schema/xsd/tei_all_dcr.xsd
    - name: Download schema file 3
      run: wget https://tei-c.org/release/xml/tei/custom/schema/xsd/tei_all_teix.xsd
    - name: Download schema file 4
      run: wget https://tei-c.org/release/xml/tei/custom/schema/xsd/tei_all_xml.xsd
    - name: Lint xml
      uses: ChristophWurst/xmllint-action@v1
      with:
        xml-file: ./tei/image-four-living-creatures.xml
        xml-schema-file: ./tei_all.xsd
